### ISSUE TITLE
Mejoras

### ISSUE THREAD

**Issue by migueldelmazo** [Adalab/modulo-1-evaluacion-intermedia-silviaespanagil#1]
Muy buen trabajo @silviaespanagil!!!

Aquí tienes unos consejos para mejorar tu ejercicio:

Puntuación: 296 / 347
- [x] HTML > LINK: El fichero de fuentes debe estar antes que nuestro fichero de estilos para que ningún fichero de estilos externo sobre escriba los nuestros.
- [x] HTML > HEADER: La etiqueta `img` debe tener el atributo `title`.
- [x] HTML > HEADER: Los enlaces tienen que tener el atributo `title`.
- [x] HTML > MAIN: El contenido exacto del h1 debe ser "Creando diversidad digital". Debemos poner las primeras letras en mayúsculas con CSS.
- [x] CSS > ESTILOS REPETIDOS: Hay estilos repetidos en las media queries que no son necesarios, es mejor quitarlos. `.header { width: 100% }`, `.header { display: flex }`
- [x] CSS > COLOR: El color del h1 debe ser blanco
- [x] CSS > FONT-SIZE: El tamaño del h1 en móvil debe ser 30px.
- [x] CSS > FONT-SIZE: El tamaño del h1 en tablet debe ser 40px.
- [x] CSS > PADDING: El padding de los enlaces no debería ser 0. Auméntalo para aumentar el área clickable, pero manteniendo los requisitos del diseño.
- [x] CSS > FLEX: El HEADER en tablet debe tener los elementos alineados a izquierda y derecha .

Es posible que cuando corrijas uno de estos puntos, otros se corrijan solos, ya que unos dependen de otros.

Y recuerda algo muy importante:

- Escribe tu código en inglés.
- Escribe todos los ficheros y carpetas en inglés.
- Los commits también tienen que ser en inglés, empezando por un verbo en infinitivo.

Ánimo y si tienes cualquier duda avísame!!!

> Con cada mejora que hagas, márcala como completada en este issue y su súbela a este repo.

> Este issue ha sido creado automáticamente por ello puede tener algún error, si hay algo que no te encaja escribe por slack al coordinador de Adalab.

> Para corregir el ejercicio buscamos determinadas palabras en el código para identificar las secciones. Por ejemplo buscamos **Creando** para buscar el título de la página. Si has escrito mal alguna palabra en el código es posible que te aparezcan aquí falsos errores.

> Por favor no cierres este issue, ya lo haremos nosotros.

**Comment by silviaespanagil** [comment]
Hola,

Gracias por  la devolución. Las siguientes tareas fueron marcadas como listas sin realizar ningún cambio ya que ya contaban con dicha característica:

 HTML > HEADER: Los enlaces tienen que tener el atributo title.
HTML > MAIN: El contenido exacto del h1 debe ser "Creando diversidad digital". Debemos poner las primeras letras en mayúsculas con CSS.
CSS > FLEX: El HEADER en tablet debe tener los elementos alineados a izquierda y derecha .

¡Gracias!

**Comment by migueldelmazo** [comment]
Hola @silviaespanagil,

Gracias por hacer las mejoras. Solo te quiero comentar una pijadilla. 

HTML > HEADER: Los enlaces tienen que tener el atributo title: los enlaces de contacto y blog no tienen title. El enlace del logo sí. Estaría bien ponerlo para dar un poco más de semántica a la página.

Un saludo.

**Comment by silviaespanagil** [comment]
¡Entiendo!

Pensé, no se por qué, que se reservaba para imágenes. Pero ahora vi que hace una especie de tooltip.

**Comment by migueldelmazo** [comment]
En realidad cualquier etiqueta incluido un párrafo, div, header... pueden tener title y aparecerán cuando poses el ratón encima. Se suele utilizar principalmente para imágenes y links, pero funciona en todos.
